# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 078d6b11db37ebc65e9748b39e4d8f917dd08d4f105602c40a68130eafb507d90e0a0d3f026e5234c795a9105a977e6211be6875fa82e0eec66e0db162fafdd1

test:
  secret_key_base: a28ed69900aa9f6962d241194a50ed20e70fe2a43a2249bfaae9ec3a8f06500f4391f82e13408389b44e344e68315acc13a25658df32d02aeb1f73f8edea6608

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
